---
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    # restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - SERVICE_TAG=${SERVICE_TAG:-dev}
      - SERVICE_NAME=${SERVICE_NAME:-mysql}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - my-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - PMA_HOST=db
      - PMA_PORT=${MYSQLDB_LOCAL_PORT}
      - PMA_ARBITRARY=1
    ports:
      - ${PMA_EXPOSE_PORT}:80
    expose:
      - ${PMA_EXPOSE_PORT}
    depends_on:
      - db
    

# Names our volume
volumes:
  my-db: